strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'
    alpine:
      imageName: 'ubuntu-16.04'
pool:
  vmImage: $(imageName)
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  env:
    GITHUB_TOKEN: $(PersonalGithubToken)
- script: |
    npm install
    npm run ci:build
